name: physiology
description: A new Flutter application.
version: 2.1.0+31
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  url_launcher: ^5.2.5
  share: ^0.6.3+6
  app_review: ^1.1.0+1
  fl_chart: ^0.5.0
  google_nav_bar: ^1.0.1
  day_night_switch: ^0.0.2+1
  expandable: ^4.0.2
  shared_preferences:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
  - images/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/OpenSans-Regular.ttf
